language: node_js

node_js:
  - 10

script:
  - yarn run format
  - yarn run lint
  - yarn run build:lib
  - yarn run test:coverage
  - yarn workspace website run build

after_success:
  - npx codecov --file=./coverage/lcov.info

notifications:
  email: false

cache:
  yarn: true
  directories:
    - 'node_modules'
